### PR TITLE
Be fault-tolerant towards missing 'owner' field in copr msgs

### PR DESCRIPTION
**Pull request by clime**

### CODE REVIEW

**Review by sayanchowdhury — APPROVED** [review]

**Comment by jeremycline** [comment]
Hey, thanks for the patch!

FMN {lib, rules, consumer} have been condensed into a singe repository: https://github.com/fedora-infra/fmn. I thought I had updated all the READMEs, but clearly I did not. Can you re-open this against fmn?

Also, the patch as it stands won't work, since the next line emits a debug statement that assumes the presence  of the 'owner' key again. It would be great to write a test case for this, but if you don't have the time/inclination I understand (especially since there's not much of a test suite at the moment) and I will write one.

**Comment by clime** [comment]
> Also, the patch as it stands won't work, since the next line emits a debug statement that assumes the presence of the 'owner' key again. 

It emits a statement only if the above condition passes and the condition passes only if `msg['msg'].get('owner') in self.ignored_copr_owners`. If `None` is in `self.ignored_copr_owners`, then it might happen what you describe but I doubt it is there.

**Comment by jeremycline** [comment]
Oh, yes, you're right. I should have more coffee.

**Comment by pypingou** [comment]
@jeremycline Should we merge this one?

**Comment by jeremycline** [comment]
@pypingou I was going to cherry-pick it over to https://github.com/fedora-infra/fmn and write tests for it.

**Comment by pypingou** [comment]
Okido :)

**Comment by jeremycline** [comment]
Merged via https://github.com/fedora-infra/fmn/commit/d46464e0659ede88ba394aff059589932f643f03

**Pull request closed without merging**
