### PR TITLE
Use the new msg2long_form API.

### PR DESCRIPTION
**Pull request by ralphbean**
Fixes fedora-infra/fmn#26.

This should make emails from fmn much more interesting (over time).

See example script below for what it does:

```python
import fedmsg
import fedmsg.config
import fedmsg.meta

config = fedmsg.config.load_config()
fedmsg.meta.make_processors(**config)

for _, _, topic, msg in fedmsg.tail_messages():
    print
    print topic
    print "-" * len(topic)
    print fedmsg.meta.msg2long_form(msg, **config)


"""
org.fedoraproject.prod.git.receive
----------------------------------
kwizart pushed to quazip (f21).  "Update to 0.7.1"

From f15b9cbefa12327bbd0b0fb19c288551d1f66748 Mon Sep 17 00:00:00 2001
From: Nicolas Chauvet <kwizart@gmail.com>
Date: Thu, 8 Jan 2015 16:49:12 +0100
Subject: Update to 0.7.1


diff --git a/.gitignore b/.gitignore
index faf1736..627f3ed 100644
--- a/.gitignore
+++ b/.gitignore
@@ -8,3 +8,4 @@ quazip-0.3.tar.gz
 /quazip-0.6.1.tar.gz
 /quazip-0.6.2.tar.gz
 /quazip-0.7.tar.gz
+/quazip-0.7.1.tar.gz
diff --git a/quazip.spec b/quazip.spec
index e081fe3..43eb7b1 100644
--- a/quazip.spec
+++ b/quazip.spec
@@ -1,6 +1,6 @@
 Name:      quazip
-Version:   0.7
-Release:   2%{?dist}
+Version:   0.7.1
+Release:   1%{?dist}
 Summary:   Qt/C++ wrapper for the minizip library
 License:   GPLv2+ or LGPLv2+
 URL:       http://quazip.sourceforge.net/
@@ -65,6 +65,9 @@ make INSTALL="install -p" INSTALL_ROOT=%{buildroot} install
 %{_libdir}/*.so

 %changelog
+* Thu Jan 08 2015 Nicolas Chauvet <kwizart@gmail.com> - 0.7.1-1
+- Update to 0.7.1
+
 * Sun Aug 17 2014 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.7-2
 - Rebuilt for https://fedoraproject.org/wiki/Fedora_21_22_Mass_Rebuild

diff --git a/sources b/sources
index 63275df..b500b77 100644
--- a/sources
+++ b/sources
@@ -1 +1 @@
-52a9d807934ce4e9c30ead677a3148d2  quazip-0.7.tar.gz
+3b99effb2a9417707d463e6f19cf2629  quazip-0.7.1.tar.gz
--
cgit v0.10.1



org.fedoraproject.prod.buildsys.build.state.change
--------------------------------------------------
karsten's ghc-regexpr-0.5.4-12.fc21 failed to build (ppc)
"""
```

### CODE REVIEW

**Comment by pypingou** [comment]
:+1: on the change, does msg2long_form fallback to msg2repr if it's not defined in fedmsg_meta_fedora_infrastructure ?

**Comment by ralphbean** [comment]
Good thought -- It *doesn't* exactly.  It falls back to ``msg2subtitle`` which does not include the link/url.  I'll need to include that manually in a subsequent commit.

**Comment by ralphbean** [comment]
> I'll need to include that manually in a subsequent commit.

Done in f3dfa33

**Comment by pypingou** [comment]
:+1: for me

**Pull request merged**
